# Generated by Django 4.2.1 on 2023-05-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description_dict", models.JSONField()),
                ("pandera_schema", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
