# Generated by Django 4.2.1 on 2023-05-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapper", "0002_schema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schema",
            name="description",
        ),
        migrations.AddField(
            model_name="schema",
            name="categories",
            field=models.JSONField(null=True),
        ),
    ]
